Update airport data
martide/airports pull request #1
Opened 2021-12-23 15:48 UTC by christianlj

2021-12-28 08:12 UTC, samhamilton commented on mix.exs
> +  @project_url "https://github.com/martide/airports"
please don't adjust this

2021-12-28 08:13 UTC, samhamilton commented on mix.exs
> +    [
@christianlj please dont adjust this either

2022-01-04 11:38 UTC, dgigafox requested changes

2022-01-04 11:38 UTC, dgigafox commented on test/airports_test.exs
> +    assert Enum.count(Airports.all()) == 69197
@christianlj @samhamilton I would suggest asserting the number of rows of airports from the csv should be equal to `Enum.count(Airports.all())`. And that all airports have non-null fields (if it applies).

2022-01-04 11:39 UTC, dgigafox approved these changes

2022-01-06 04:43 UTC, merged